services:
  - type: web
    name: fieldpulse
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login.php
    envVars:
      - key: DB_DRIVER
        value: sqlite
      - key: BASE_URL
        value: ""
      - key: APP_ENV
        value: production
      - key: PHP_INI_SCAN_DIR
        value: /usr/local/etc/php/conf.d