services:
  - type: web
    name: fieldpulse
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login.php
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: field_service_db
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: ""
      - key: BASE_URL
        value: ""